# Generated by Django 3.1.6 on 2021-05-17 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0017_article_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(db_table='article_likes', related_name='blog_acticles', to=settings.AUTH_USER_MODEL),
        ),
    ]
