# Generated by Django 3.1.6 on 2021-05-17 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0018_auto_20210517_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(db_table='comment_likes', related_name='blog_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
